[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"  
watchPatterns = [
    "requirements.txt", 
    "src/**", 
    "railway.toml",
    "Dockerfile",
]

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[vars]
PORT = "8000"