"""updated table

Revision ID: 38b62ee771bb
Revises: 
Create Date: 2025-07-11 16:47:05.133177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b62ee771bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('flight',
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('flight_id', sa.String(), nullable=False),
    sa.Column('total_price', sa.String(), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('departure_date', sa.DateTime(), nullable=False),
    sa.Column('arrival_date', sa.DateTime(), nullable=False),
    sa.Column('departure_location', sa.String(), nullable=False),
    sa.Column('arrival_location', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index(op.f('ix_flight_booking_id'), 'flight', ['booking_id'], unique=False)
    op.create_table('hotel',
    sa.Column('hotel_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('check_in_date', sa.DateTime(), nullable=False),
    sa.Column('check_out_date', sa.DateTime(), nullable=False),
    sa.Column('amenities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('room_details', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('hotel_location', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('hotel_id')
    )
    op.create_index(op.f('ix_hotel_hotel_id'), 'hotel', ['hotel_id'], unique=False)
    op.create_table('itinerary',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('flights', sa.JSON(), nullable=True),
    sa.Column('hotels', sa.JSON(), nullable=True),
    sa.Column('attractions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_id'), 'itinerary', ['id'], unique=False)
    op.create_index(op.f('ix_itinerary_title'), 'itinerary', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itinerary_title'), table_name='itinerary')
    op.drop_index(op.f('ix_itinerary_id'), table_name='itinerary')
    op.drop_table('itinerary')
    op.drop_index(op.f('ix_hotel_hotel_id'), table_name='hotel')
    op.drop_table('hotel')
    op.drop_index(op.f('ix_flight_booking_id'), table_name='flight')
    op.drop_table('flight')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
